#语言设置
#Language setting
lang: en_US

#累计减少多少饱食度就会屯一坨屎
#Decide how many food levels when a player lost, a shit will stored in this player's belly
poopwhenfoodlost: 20

#累计屯了几坨屎就会憋不住
#Decide how many shit can store in player's belly
poopcansave: 4

#不会拉屎的人的白名单
#White list of people who can not shit
whitelist:
- '0f2aa1aa-809a-49cf-8800-bb519a64a93f'

#马桶的完整自定义ID (用于判断是否为马桶, 建议不要修改)
#The complete custom ID of the toilet
#(Used to determine whether it is a toilet, it is not recommended to modify)
toiletid: 'shit:toilet'

#屎的完整自定义ID (用于生成屎, 建议不要修改)
#The complete custom ID of the shit
#(Used to generate shit, it is not recommended to modify)
shitid: 'shit:shit'
